### ISSUE TITLE
Build the volunteer sign-up page

### ISSUE THREAD

**Issue by iAmWillShepherd** [wnjnz/Assyst#1]
Volunteers need a way to signup and commit to an event. Ideally, they'd have a profile that has something about them, skills, and other relevant info.

**Comment by iAmWillShepherd** [comment]
This includes building a sign-in page

**Comment by wnjnz** [comment]
https://cdn.cp.adobe.io/content/2/dcx/ebf34e75-51bd-4522-ad7f-9b8820edeba1/content/artwork/artboard-902bab28-c653-4f01-9a60-511a27e0eb1e/graphicContent.png/version/0

**Comment by wnjnz** [comment]
![0 1](https://user-images.githubusercontent.com/12652734/30044229-9f3ef8ec-91c1-11e7-8aee-5275333c6eae.png)

**Comment by wnjnz** [comment]
![0 2](https://user-images.githubusercontent.com/12652734/30044239-a9ac2214-91c1-11e7-9605-fe9124ce1da3.png)

**Comment by wnjnz** [comment]
![0 3](https://user-images.githubusercontent.com/12652734/30044248-b1d3688a-91c1-11e7-8952-8e2e201f5b03.png)

**Comment by wnjnz** [comment]
![0 4](https://user-images.githubusercontent.com/12652734/30044260-bc6569e2-91c1-11e7-8395-2dfebbf518bf.png)

**Comment by wnjnz** [comment]
![0 5](https://user-images.githubusercontent.com/12652734/30044267-c7bc5fd0-91c1-11e7-8c21-ab0700e7cd3a.png)

**Comment by wnjnz** [comment]
https://xd.adobe.com/view/ebf34e75-51bd-4522-ad7f-9b8820edeba1/screen/dda14872-ac11-47c4-b607-3f8a7e6955ab/iPhone-6-7-Opportunities-2

**Comment by wnjnz** [comment]
[sign-up mockup](https://github.com/wnjnz/asys/blob/master/docs/mockups/2signup.png)

**Comment by iAmWillShepherd** [comment]
See issue #4

**Comment by iAmWillShepherd** [comment]
During the signup process, we need to capture information about the volunteer, so that we can match place volunteers in roles where they will have the most impact. Some of the info needed includes:
 * Specialized skills i.e. licenses, training, advanced/professional education
 * Location
 * Willingness to travel
 * Emergency contact info
